import type { UserNavigation } from '../my-types'
import  GlobalNavigation from './ui/globalnav'
import { Radio_Canada, Saira_Extra_Condensed } from "next/font/google";
import "./globals.css";
import {getTheme} from './getTheme'
import { Suspense, useState } from 'react';



export const radio_canada = Radio_Canada({ subsets: ["latin"], weight: "300" });
export const radio_canada_bold = Radio_Canada({ subsets: ["latin"], weight: "400" });
export const saira_extra_condensed = Saira_Extra_Condensed({subsets: ["latin"], weight: "400"});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const userNavigation: UserNavigation[] = [
  {name: 'Your Profile', href: '#'},
  {name: 'Settings', href: '#' },
  {name: 'Sign out', href: '#'},
]

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  

    return (
    
      <html lang="en" className="bg-white dark:bg-black bg-no-repeat min-h-full 
        motion-reduce:transition-none dark:text-white transition-all duration-[1500ms]">
        
        {/*duration-[1500ms] */}
        {/*transition-all */}
        <head>
          <script dangerouslySetInnerHTML={{ __html: getTheme }} />
        </head>
        <body className={`${radio_canada.className}`}>
        <Suspense fallback={<p></p>}>
        
          <div className="min-h-full">
            <header className="fixed z-50 w-full h-fit text-black dark:text-gray-400 dark:bg-black/50 bg-white-400/50 backdrop-filter backdrop-blur-[5px]">
              <GlobalNavigation userNavigation={userNavigation} /> 
            </header>
            {children}
          </div>
        </Suspense>
        </body>
      </html>
  );
}
